services:
  - type: web
    name: lark-mail-automation
    env: python
    buildCommand: pip install --no-cache-dir -r requirements.txt
    startCommand: gunicorn src.main:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: ENVIRONMENT
        value: production
      - key: LARK_WEBHOOK_URL
        sync: false